[package]
name = "torchft"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
log = "0.4.22"
raft = "0.7.0"
slog = "2.7.0"
slog-stdlog = "4.1.1"
stderrlog = "0.6.0"
tokio = {version = "1.40.0", features = ["full", "test-util", "tracing"] }
